name: Check for updates

on:
  schedule:
    - cron: '52 3/6 * * *'
  push:

jobs:
  check:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/wjt/flatpak-external-data-checker:force-no-fork
        env:
          GIT_AUTHOR_NAME: Endless External Data Checker
          GIT_COMMITTER_NAME: Endless External Data Checker
          GIT_AUTHOR_EMAIL: os@endlessos.org
          GIT_COMMITTER_EMAIL: os@endlessos.org
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            --verbose --update --force-no-fork com.google.Chrome.json
